# title: ds_template
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

permalink: pretty

search_enabled: true
auto_page_title: false

mermaid_enabled: true
mermaid_theme: forest

sidebar:
  - label: Postgresql Development
    children:
      - sessiondata
      - retention_queries
      - postgres_py_recurrence_eval
  - label: Jupyter and Python DS Templates
    children:
      - cross_validation
      - feature_selection
      - grid_search_hyperopt
      - jupyter_pandas_basics
      - metric_performance_evaluation
      - shap_clustering
      - shap_value_visualizations
  - label: Donor Exploration
    children:
      - donor_data
  - label: Site Editing How-tos
    children:
      - getting-started
      - sidebar
      - search
      - relative-nav
      - additional-config
      - development

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: default
