# title: ds_template
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

permalink: pretty

search_enabled: true
auto_page_title: false

mermaid_enabled: true
mermaid_theme: forest

sidebar:
  - label: Site Editing How-tos
    children:
      - getting-started
      - sidebar
      - search
      - relative-nav
      - additional-config
      - development
  - label: Postgresql Development
    children:
      - sessiondata
      - retention_queries
      - postgres_py_recurrence_eval
  - label: Donor Exploration
    children:
      - donor_data

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: default
